### ISSUE TITLE
Error While Building Project!

### ISSUE THREAD

**Issue by csm-18** [chaoyangnz/zava#1]
Hello, @chaoyangnz!
I was trying to build the project and got error like this:
![error-while-build-project-zava](https://github.com/user-attachments/assets/6c99d006-6de9-45b4-955e-c17883344ffb)

Is it because of zig version difference?

**Comment by chaoyangnz** [comment]
What is your version?

**Comment by csm-18** [comment]
zig version: 0.13.0

**Comment by csm-18** [comment]
So, in the build.zig file:
![image](https://github.com/user-attachments/assets/a1e2c90f-baeb-452b-9240-7767467bfabc)
Ok, so according to zig docs for 0.13.0, the thing that changed is:
![image](https://github.com/user-attachments/assets/c87631df-7a0e-474e-8ca1-06ae9327cedf)

This worked, but still getting some other errors.

**Comment by chaoyangnz** [comment]
Updated to adapt v0.13.0. please pull

**Comment by csm-18** [comment]
I did the pull and rebuilt it and it produced the exe. But, when I run the exe, it gives the output:


![image](https://github.com/user-attachments/assets/9d54f27d-ae2b-40e6-9ea9-af267fde6cc0)

**Comment by chaoyangnz** [comment]
How did you run it?

**Comment by csm-18** [comment]
First I tried this:
```
./zig-out/bin/zava
```

For which i got the above Ouput.

Then I copied the binary to classes folder and :


```
./zava HelloWorld.class
```

But still get error!

**Comment by chaoyangnz** [comment]
In the root folder, make sure you pull the sub module jdk, then run

./zava HelloWorld

Without .class, without copying binary to classes folder

**Comment by csm-18** [comment]
The sub module jdk path gives 404 error!

**Comment by chaoyangnz** [comment]
download from this page: https://github.com/chaoyangnz/zava/wiki/JDK

**Comment by csm-18** [comment]
It worked!

![image](https://github.com/user-attachments/assets/a02db1dd-5371-4d07-bd35-705bc63591ff)

Thank you!
